import "./globals.css";
import Navbar from "./components/Navbar/index";
import Footer from "./components/Footer/index";
import { Analytics } from "@vercel/analytics/next";

export const metadata = {
	title: "KopiHerbalku - Kopi Herbal Terbaik Se-Indonesia",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="flex flex-col h-screen justify-between">
				<Analytics />
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
